# Generated by Django 4.0.4 on 2022-06-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone_de_contato',
            field=models.CharField(default='000-0000', max_length=32, verbose_name='Telefone de contato'),
        ),
    ]
