# Generated by Django 4.0.5 on 2022-07-02 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(upload_to='icones/empresas')),
                ('operadores', models.ManyToManyField(related_name='minha_lista_de_empresas', related_query_name='minhas_empresas', to=settings.AUTH_USER_MODEL, verbose_name='Operadores da empresa')),
            ],
        ),
    ]
