# Generated by Django 4.0.5 on 2022-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_da_empresa',
            field=models.CharField(blank=True, default='Empresa', max_length=512, verbose_name='Nome da empresa'),
        ),
    ]
